# Generated by Django 3.2.7 on 2021-11-10 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidopaterno', models.CharField(max_length=50)),
                ('apellidoMaterno', models.CharField(max_length=50)),
                ('estadoCivil', models.CharField(max_length=8)),
                ('sexo', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consuctor',
                'verbose_name_plural': 'Consuctors',
            },
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('caballosFuerza', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('motor', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionMaquinaria.conductor')),
            ],
            options={
                'verbose_name': 'Maquinaria',
                'verbose_name_plural': 'Maquinarias',
            },
        ),
    ]
