# Generated by Django 3.2.7 on 2021-11-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMaquinaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conductor',
            options={'verbose_name': 'Conductor', 'verbose_name_plural': 'Conductors'},
        ),
    ]
